import 'dart:convert';

import 'package:magichiberus/domain/entities/carta_entitie.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

class CartasProvider extends ChangeNotifier{
  List<Carta> listaCartas = [];
  
  CartasProvider(){
    this.getAllCards();
  }
  
  getAllCards() async {
    var urlMagicAPI = Uri.parse('https://api.magicthegathering.io/v1/cards');
    var response = await http.get(urlMagicAPI);

    listaCartas = parseadoCartas(response.body);
    print(listaCartas.elementAt(0).name);
  }

  List<Carta> parseadoCartas(String responseBody){
    final parseado = json.decode(responseBody).cast<String, dynamic>();
    return Autogenerated.fromJson(parseado).cartas;
  }
  
}