class Autogenerated {
  List<Carta> cartas = [];

  Autogenerated({required this.cartas});

  Autogenerated.fromJson(Map<String, dynamic> json) {
     if (json['cards'] != null) {
      json['cards'].forEach((v) {
        cartas.add(new Carta.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.cartas != null) {
      data['cards'] = this.cartas.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Carta {
  String name;
  String? manaCost;
  double cmc;
  String type;
  String? rarity;
  String set;
  String setName;
  String? text;
  String? flavor;
  String artist;
  String number;
  String? power;
  String? toughness;
  String layout;
  String? multiverseid;
  String imageUrl;
  String? originalText;
  String? originalType;
  String? watermark;
  String id;

  Carta(
      {required this.name,
        this.manaCost,
        required this.cmc,
        required this.type,
        this.rarity,
        required this.set,
        required this.setName,
        this.text,
        this.flavor,
        required this.artist,
        required this.number,
        this.power,
        this.toughness,
        required this.layout,
        this.multiverseid,
        required this.imageUrl,
        this.originalText,
        this.originalType,
        this.watermark,
        required this.id,});

  factory Carta.fromJson(Map<String, dynamic> json) {
    String imageURL = "";
    if (json['imageUrl'] != null){
      imageURL = json['imageUrl'];
    }
    return Carta(
      name : json['name'],
      manaCost : json['manaCost'],
      cmc : json['cmc'],
      type : json['type'],
      rarity : json['rarity'],
      set : json['set'],
      setName : json['setName'],
      text : json['text'],
      flavor : json['flavor'],
      artist : json['artist'],
      number : json['number'],
      power : json['power'],
      toughness : json['toughness'],
      layout : json['layout'],
      multiverseid : json['multiverseid'],
      imageUrl : imageURL,
      originalText : json['originalText'],
      originalType : json['originalType'],
      watermark : json['watermark'],
      id : json['id'],
    );

  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['manaCost'] = this.manaCost;
    data['cmc'] = this.cmc;
    data['type'] = this.type;
    data['rarity'] = this.rarity;
    data['set'] = this.set;
    data['setName'] = this.setName;
    data['text'] = this.text;
    data['flavor'] = this.flavor;
    data['artist'] = this.artist;
    data['number'] = this.number;
    data['power'] = this.power;
    data['toughness'] = this.toughness;
    data['layout'] = this.layout;
    data['multiverseid'] = this.multiverseid;
    data['imageUrl'] = this.imageUrl;
    data['originalText'] = this.originalText;
    data['originalType'] = this.originalType;
    data['id'] = this.id;
    data['watermark'] = this.watermark;
    return data;
  }
}