import 'dart:convert';

import 'package:magichiberus/domain/entities/carta_entitie.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

class CartasProvider extends ChangeNotifier {
  List<Carta> listaCartas = [];
  
  CartasProvider() {
    this.getAllCartas();
  }
  
  Future<List<Carta>> getAllCartas() async {
    var urlMagicAPI = Uri.parse('https://api.magicthegathering.io/v1/cards');
    var response = await http.get(urlMagicAPI);

    return listaCartas = parseadoCartas(response.body);
  }

  List<Carta> parseadoCartas(String responseBody){
    final parseado = json.decode(responseBody).cast<String, dynamic>();
    return Autogenerated.fromJson(parseado).cartas;
  }
  
}